name: easier_drop
description: "App Flutter desktop para coletar arquivos temporariamente e arrastar em lote para outro destino."
publish_to: 'none'
version: 1.0.4
repository: https://github.com/victorcmarinho/EasierDrop

environment:
  sdk: ^3.7.0

dependencies:
  window_manager: ^0.5.1
  provider: ^6.1.5+1
  share_plus: ^12.0.0
  tray_manager: ^0.5.1
  cupertino_icons: ^1.0.8
  macos_ui: ^2.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  text_marquee: ^0.0.2
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0
  pub_semver: ^2.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  path_provider_platform_interface: ^2.1.2
  mocktail: ^1.0.4
  mockito: ^5.5.1
  build_runner: ^2.9.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon/icon.icns

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  untranslated-messages-file: l10n_untranslated.txt
  synthetic-package: false
  nullable-getter: false


macos:
  min_os_version: '10.15'
