name: easier_drop
description: "App Flutter desktop para coletar arquivos temporariamente e arrastar em lote para outro destino."
publish_to: 'none'
version: 1.1.2
repository: https://github.com/victorcmarinho/EasierDrop

environment:
  sdk: ^3.10.0

dependencies:
  window_manager: ^0.5.1
  provider: ^6.1.5+1
  share_plus: ^12.0.0
  tray_manager: ^0.5.1
  cupertino_icons: ^1.0.8
  macos_ui: ^2.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  http: ^1.6.0
  pub_semver: ^2.2.0
  package_info_plus: ^8.3.1
  url_launcher: ^6.3.2
  desktop_multi_window: ^0.3.0
  shimmer: ^3.0.0
  aptabase_flutter: ^0.4.1
  pasteboard: ^0.4.0
  marquee_text: ^2.5.0+1
  meta: ^1.11.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  path_provider_platform_interface: ^2.1.2
  mocktail: ^1.0.4
  mockito: ^5.5.1
  build_runner: ^2.9.0
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
  
    - path: assets/icon/icon.png
      platforms:
        - macos
    - path: assets/icon/icon.icns
      platforms:
        - macos
    - path: assets/promo/demo.webp
      platforms:
        - web
    - path: CHANGELOG.md
      platforms:
        - web
    - path: CHANGELOG_pt.md
      platforms:
        - web    
    - path: CHANGELOG_es.md
      platforms:
        - web


l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  untranslated-messages-file: l10n_untranslated.txt
  synthetic-package: false
  nullable-getter: false


macos:
  min_os_version: '13.5'
